version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - depguard
    - err113
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godox
    - lll
    - nakedret
    - nlreturn
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 150
      statements: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
