version: "3.9"
services:
    anti-bruteforce:
        build:
         context: ../
         dockerfile: Dockerfile
        ports:
         - "55555:55555" # gRPC API
        depends_on:
         - migrate
        volumes:
         - ./../configs/anti-bruteforce.yml:/etc/anti-bruteforce/anti-bruteforce.yml

    migrate:
        image: migrate/migrate:v4.17.1
        command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
        depends_on:
          postgres:
            condition: service_healthy
        volumes:
         - ./../migrations:/migrations

    # Create service with PostgreSQL.
    postgres:
        image: postgres:16.3-alpine3.20
        ports:
         - "${POSTGRES_PORT}"
        user: root
        env_file:
         - postgres.env
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
        volumes:
         - ${HOME}/volumes_docker/anti-bruteforce/postgres-data:/var/lib/postgresql/data
