version: "3"
services:
    calendar:
        build:
         context: ../
         dockerfile: cmd/calendar/Dockerfile
        ports:
         - "8080:8080"
        environment:
         ENV: PROD
        links:
         - postgres
    postgres:
        image: postgres:latest
        environment:
         POSTGRES_PASSWORD: event-db
         POSTGRES_USER: event-db
         POSTGRES_DB: event-db
