# GRPC client settings
grpc:
    host: localhost
    port: 55555

# HTTP server setting
http:
    host: localhost
    port: 8080

# logging settings
logger:
    filepath: log.json
    level: debug # debug, info, warn, error
