client: "grpc"

# HTTP client settings
http-client:
    host: backend
    port: 8088

# GRPC client settings
grpc-client:
    host: backend
    port: 55555

# HTTP server setting
http:
    host: frontend
    port: 8080

# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    enable: true
    host: otel_collector
    port: 4317

# metric settings
metrics:
    enable: true
    host: otel_collector
    port: 4317
