# GRPC client settings
grpc:
    host: localhost
    port: 55555

# HTTP server setting
http:
    host: localhost
    port: 8080

# logging settings
logger:
    filepath: calendar-ws-log.json
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    enable: false
    host: otel_collector
    port: 4317

# metric settings
metrics:
    enable: false
    host: otel_collector
    port: 4317
