# GRPC client settings
grpc:
    host: calendar
    port: 55555

# HTTP server setting
http:
    host: calendar-ws
    port: 8080

# logging settings
logger:
    filepath: log.json
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    host: otel_collector
    port: 4317

# metric settings
metrics:
    host: otel_collector
    port: 4317
