# GRPC server settings
grpc:
    host: localhost
    port: 55555

# HTTP server setting
http:
    host: localhost
    port: 8088
    is_https: true # Enable HTTPS
    https:
        cert_file: ../cert/serverCert.pem
        key_file: ../cert/serverKey.pem
        client_cert_file: ../cert/clientCert.pem

inmemory: true

# database settings
db:
    driver: postgres
    host: localhost
    port: 5432
    user: event-db
    password: event-db
    name: event-db

# logging settings
logger:
    filepath: ../logs/calendar-log.json
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    enable: false
    host: otel_collector
    port: 4317

# metric settings
metrics:
    enable: false
    host: otel_collector
    port: 4317

# JWT auth
auth:
    secret_key: PNvEBrLW+zU7SPi+nqmY5KD6FVecuQW1VHFRUI8xAGKM4JnIvR3zQescAq
    token_validity_period: 15	 # in minutes
