client: "grpc"

# HTTP client settings
http-client:
    host: localhost
    port: 8088

# GRPC client settings
grpc-client:
    host: localhost
    port: 55555

# HTTP server setting
http:
    host: localhost
    port: 8080

# logging settings
logger:
    filepath: ../logs/calendar-front-log.json
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    enable: false
    host: otel_collector
    port: 4317

# metric settings
metrics:
    enable: false
    host: otel_collector
    port: 4317
