# GRPC server settings
grpc:
    host: calendar
    port: 55555

# HTTP server setting
http:
    host: calendar
    port: 8088
    is_https: false # Enable HTTPS
    https:
        cert_file: ../cert/cert.pem
        key_file: ../cert/key.pem

inmemory: false

# database settings
db:
    host: postgres
    port: 5432
    user: event-db
    password: event-db
    name: event-db

# logging settings
logger:
    filepath: log.json
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    host: jaeger
    port: 14268
