# GRPC server settings
grpc:
    host: calendar
    port: 55555

# HTTP server setting
http:
    host: calendar
    port: 8088
    is_https: false # Enable HTTPS
    https:
        cert_file: ../cert/serverCert.pem
        key_file: ../cert/serverKey.pem
        client_cert_file: ../cert/clientCert.pem

inmemory: false

# database settings
db:
    driver: postgres
    host: postgres
    port: 5432
    user: event-db
    password: event-db
    name: event-db

# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error

# tracing settings
tracer:
    enable: true
    host: otel_collector
    port: 4317

# metric settings
metrics:
    enable: true
    host: otel_collector
    port: 4317
