name: Docker Image Scheduler CI

on:
  push:
    paths:
     - 'hw12-15calendar/services/scheduler/**'
     - 'hw12-15calendar/internal/**'
     - '!hw12-15calendar/internal/calendarapi/**'
  pull_request:
     paths:
     - 'hw12-15calendar/services/scheduler/**'
     - 'hw12-15calendar/internal/**'
     - '!hw12-15calendar/internal/calendarapi/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build hw12-15calendar/ --file hw12-15calendar/services/scheduler/Dockerfile --tag scheduler:$(date +%s)
