name: Docker Image Sender CI

on:
  push:
    paths:
     - 'hw12-15calendar/services/sender/**'
     - 'hw12-15calendar/internal/**'
     - !'hw12-15calendar/internal/calendarapi/**'
     - !'hw12-15calendar/internal/storage/**'
  pull_request:
     paths:
     - 'hw12-15calendar/services/sender/**'
     - 'hw12-15calendar/internal/**'
     - !'hw12-15calendar/internal/calendarapi/**'
     - !'hw12-15calendar/internal/storage/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build hw12-15calendar/ --file hw12-15calendar/services/sender/Dockerfile --tag sender:$(date +%s)
