# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build/Test Calendar CI

on:
  push:
    paths:
     - 'hw12-15calendar/services/calendar/**'
     - 'hw12-15calendar/internal/**'
     - '!hw12-15calendar/internal/queue/**'
  pull_request:
     paths:
     - 'hw12-15calendar/services/calendar/**'
     - 'hw12-15calendar/internal/**'
     - '!hw12-15calendar/internal/queue/**'

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.0-alpine
        env:
          POSTGRES_PASSWORD: event-db
          POSTGRES_USER: event-db
          POSTGRES_DB: event-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      run: cd hw12-15calendar/services/calendar && make build

    - name: Test
      run: |
        sed -i 's/postgres/localhost/g' hw12-15calendar/services/calendar/httpserver/handler_test.go
        sed -i 's/postgres/localhost/g' hw12-15calendar/internal/storage/sql/storage_test.go
        cd hw12-15calendar/services/calendar && make test
